### ISSUE TITLE
Bart submission

### ISSUE THREAD

**Issue by AnnaMatysiak** [dataanalysis3/testAssignment2019#4]
Bart does not accept the Word document, is it fine to submit the pdf file? 
Anna

**Comment by abessudnov** [comment]
Yes, any format is fine, although Bart should accept Word.

(Next time you open an issue could you please do it here - https://github.com/dataanalysis3/datan3_2019/issues ?)

**Comment by AnnaMatysiak** [comment]
Yes of course, thank you!
